[package]
name = "sherpa-s3"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[[bin]]
name = "sherpa"
path = "src/main.rs"

[dependencies]
aws-sdk-s3 = "1.118.0"
clap = "4.5.53"
tokio = "1.48.0"
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
